function cond_dist_z_figure(X1, Y1, yvector1)
%CREATEFIGURE(X1, Y1, YVECTOR1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  YVECTOR1:  area yvector

%  Auto-generated by MATLAB on 18-Dec-2018 14:17:46

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create area
area(X1,yvector1,'Parent',subplot1,'FaceColor',[0.65 0.65 0.65],...
    'LineStyle','none');

% Create plot
plot(X1,Y1,'Parent',subplot1,'LineWidth',2,'Color',[0 0 0]);
axis([min(X1) max(X1) min(Y1) max(Y1)*1.2])

set(subplot1,'FontSize',14,'XTick',[-4 -3 -2 -1.8 -1 0 1 1.8 2 3 4],...
    'XTickLabel',{'-4','-3','-2','|z''_i|','-1','0','1','|z''_i|','2','3','4'});

% Create title
title({'Extreme outcomes more newsworthy'});
xlabel('z_j')

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0 0.5]);
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',14);
% Create line
% annotation(figure1,'line',[0.353125 0.353125],...
%     [0.584152838427948 0.748471615720524],'LineStyle','--');
